! Formatted Output Example

PROGRAM format_spec
    IMPLICIT NONE
    INTEGER :: i = 12345
    REAL :: j = 85.1234567890
    ! Note that REAL in FORTRAN means Single precision floating point which has 23 mantissa bits, 
    ! meaning a precison of log_10(2^23)~6.9 digits

    ! REAL*8 :: k = 5.1234567890123456789
    DOUBLE PRECISION :: k = 5.1234567890123456789
    ! This is how Double Precision FLoating point number is declared, either by
    ! REAL*8 or DOUBLE PRECISION
    ! NOTE: in this precision, exponentiation is writted as 5.4D6 = 5.4 x 10^6
    ! Note the 'D' in place of 'E'

    ! NOTE: So, likewise to declare a real number for real arithmatic, we use 5.0 (REAL) in place of 5 (INTEGER)
    ! For, DOUBLE PRECISION, we use 5.0d0 which means 5.0 x 10^0 = 5 (DOUBLE)

    REAL, DIMENSION(5) :: v = (/1.1, 1.2, 1.4, 1.6, 1.9/)       ! Array of 5 REALs

    ! SYNTAX :
    ! PRINT '(nix)', <parameters>
    ! n means number of variables to be printed in the same format
    ! x means number of characters to be printed
    
    ! For INTEGER '(nix)'
    ! For CHARACTER '(nax)'
    ! For REAL in floating point '(nfx.y)'      ! y means certainly the precision value we want
    ! For REAL in exponential '(nex.y)'

    ! So, for free formatting, we put * there

    ! testing out INTEGER
    PRINT *, i                  ! * means FREE_FORMAT
    PRINT '(i4)', i             ! 4 means 4 characters to be printed, since i has 5 digits, thus it can not print 4 characters 
                                !giving error of **** (count: 4)
    PRINT '(i5)', i             ! Now, this is perfect, 5 digit is what we needed
    PRINT '(i6)', i             ! If we choose >5, then the extras will be spaces before the output value
    PRINT '(i8)', i             ! Thus, this output has 8-5=3 spaces in front
    ! FUN FACT
    PRINT '(i8.3)', i           ! .y doesn't give error for INTEGER Data Type

PRINT *, '-----------------'    ! You might notice, FORTRAN doesn't use indentation, thus it won't matter
    ! testing out REAL
    PRINT '(f0.5)', j           ! So, 0. means the default number of characters to be printed
    PRINT '(f3.5)', j           ! For other than 0, we must need to specify the correct digit, else it will give error,
                                !which is natural cause we want 3 character to be printer whereas we want 5 precision meaning
                                !a number of 5 + <digits before decimal point> + 1 (decimal point) (= 5+2+1 = 8 here)
    PRINT '(f8.5)', j
    PRINT '(f9.5)', j           ! As like before, if we choose >8 (here), extras will be spaces
    PRINT '(f11.8)', j          ! Same as '(f0.8)'
    PRINT '(f12.9)', j
    PRINT '(f13.10)', j         ! You might have noticed already that since single precision float have accuracy of ~7 digits, thus 
                                !all other digits are random (not random, actually generated by the binary that was stored)
    PRINT '(f0.30)', j          ! You can notice that the maximum digit is of 19 decimal point length (even tho they are 'randomized')

PRINT *, '-----------------' 
    PRINT *, j
    PRINT *, k                  ! Somehow it seems k is also acting like the single precision floats!
    PRINT *, v                  ! Default format for arrays
                                ! You might notice the values are different than the one we wanted to store, it is because of precision (D2B conversion)
    PRINT '(5f8.3)', v          ! 5 REAL no, each has a width of 8 of which 3 is for the fractional part
PRINT *, '-----------------'
    PRINT '(2f8.3)', v          ! <5 means, only that numbers are put in each line

    PRINT '(e10.3)', j          ! Exponential no each has a width of 10 of which 3 is reserved for the exponetial part
    PRINT '(e10.6)', j          ! We got 10 stars, cause character to be displayed is more than our desired precision (0. is not default here unlike f0.y)
    ! The min total character required to display y precision is = 2 ('0.') + y + 2 ('E+' or 'E-') + 2 (digits in exponent)
    ! In our case we need 2 + 6 + 4 = 12
    PRINT '(e14.6)', j          ! >12 means additional 2 spaces

    ! Writing multiple data types together
    PRINT '(i5, f20.12)', i, j              ! To display INTEGER and REAL alongside
    PRINT '(i5, f4.6)', i                   ! So you can put more format specifiers than the variables for OUTPUT
    PRINT *, "TEXT", i, "TEXT2", j          ! So, in free form formatting, we can put string along with the variables
    PRINT '(A, i6, 1x, A, f18.12, 2x, A, f18.12)', "Integer next", i, "Single next" , j, "Double next", k
    ! Thus A means Character, whereas 1x, 2x means blank spaces
    ! Aw is the general form with w=width of the character to be printed

END PROGRAM format_spec